# This file must be in the same directory as the binary.
# Place the harmonic, rotational constants, and fundamental frequencies here.
harm = [3943.976, 3833.989, 1651.332, 0.02, 0.0, 0.0, 0.0, 0.0, 0.0]
rots = [14.5054957, 9.2636424, 27.6557350]
fund = [3753.156, 3656.489, 1598.834] 
# Place the genetic algorithm parameters here.
number_atoms = 3
population_size = 2000
tournament_size = 150
mutation_rate = 0.20
mutation_strength = 5e-9
fitness_threshold = 1.0
# Place the paths to the input files here if they are not in the same directory as the binary.
initial_guess = "/home/mvee/rust/fegenetics/tests/water_test"
spectro_path = "./spectro"
spectro_in_path = "./spectro_in"
